#pragma once

#include <drogon/drogon.h>
#include <cstdint>
#include <functional>
#include <string>

/*
  This query computes the tile bounds in Web Mercator and returns a vector tile generated by PostGIS.
*/

class TileService
{
    public:
        using TileCallback = std::function<void(bool success, std::string tileData, std::string errorMessage)>;

        static void getRestrictedTile(std::int64_t userId, int z, int x, int y, TileCallback&& callback);

    private:
        static bool validTileCoordinate(int z, int x, int y);
};
